// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3Xr-bC8utVCFUCsqJgmY_RTVczPKhjRE',
    appId: '1:337438022636:web:b275bd8fd31057ab3fbec9',
    messagingSenderId: '337438022636',
    projectId: 'to-bus-tracking',
    authDomain: 'to-bus-tracking.firebaseapp.com',
    storageBucket: 'to-bus-tracking.firebasestorage.app',
    measurementId: 'G-04SCD4PVW1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKOUmGl-uU6Jmjl0vYCzSSb6C2sAgXwQE',
    appId: '1:337438022636:android:1e8e9d639d6b82253fbec9',
    messagingSenderId: '337438022636',
    projectId: 'to-bus-tracking',
    storageBucket: 'to-bus-tracking.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrtUIGYdP8DuPwwooSpymHv9pRBwZwFJo',
    appId: '1:337438022636:ios:53119c49f99d4ee73fbec9',
    messagingSenderId: '337438022636',
    projectId: 'to-bus-tracking',
    storageBucket: 'to-bus-tracking.firebasestorage.app',
    iosBundleId: 'com.example.busApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrtUIGYdP8DuPwwooSpymHv9pRBwZwFJo',
    appId: '1:337438022636:ios:53119c49f99d4ee73fbec9',
    messagingSenderId: '337438022636',
    projectId: 'to-bus-tracking',
    storageBucket: 'to-bus-tracking.firebasestorage.app',
    iosBundleId: 'com.example.busApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3Xr-bC8utVCFUCsqJgmY_RTVczPKhjRE',
    appId: '1:337438022636:web:a6a7ba55b17530ba3fbec9',
    messagingSenderId: '337438022636',
    projectId: 'to-bus-tracking',
    authDomain: 'to-bus-tracking.firebaseapp.com',
    storageBucket: 'to-bus-tracking.firebasestorage.app',
    measurementId: 'G-JK90ZYBE70',
  );
}
