// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoTBjKf6yuDhYz-aKkPo6c19LM-U4Zglw',
    appId: '1:998568775119:web:ea2a824d574bb2a6e396ba',
    messagingSenderId: '998568775119',
    projectId: 'tobis-app',
    authDomain: 'tobis-app.firebaseapp.com',
    storageBucket: 'tobis-app.firebasestorage.app',
    measurementId: 'G-G82MBCS5J7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZa-EKNWZi7HjH5tOqFTIeBy-vxRfM7Xs',
    appId: '1:998568775119:android:ad0b02f3a91dc361e396ba',
    messagingSenderId: '998568775119',
    projectId: 'tobis-app',
    storageBucket: 'tobis-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtjeOefA4GzYQ1n1NlFwc57JEWEZJFttY',
    appId: '1:998568775119:ios:e3f06e70fcc27b89e396ba',
    messagingSenderId: '998568775119',
    projectId: 'tobis-app',
    storageBucket: 'tobis-app.firebasestorage.app',
    iosBundleId: 'com.example.busApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtjeOefA4GzYQ1n1NlFwc57JEWEZJFttY',
    appId: '1:998568775119:ios:e3f06e70fcc27b89e396ba',
    messagingSenderId: '998568775119',
    projectId: 'tobis-app',
    storageBucket: 'tobis-app.firebasestorage.app',
    iosBundleId: 'com.example.busApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBoTBjKf6yuDhYz-aKkPo6c19LM-U4Zglw',
    appId: '1:998568775119:web:ea2a824d574bb2a6e396ba',
    messagingSenderId: '998568775119',
    projectId: 'tobis-app',
    authDomain: 'tobis-app.firebaseapp.com',
    storageBucket: 'tobis-app.firebasestorage.app',
    measurementId: 'G-G82MBCS5J7',
  );
}
